stages:
  - source-check
  
source-check:
  stage: source-check
  needs: ['install']
  script:
    - npm run source:check

include:
  - project: virginmediaO2/digital/digital-msa/images/pipeline-templates
    ref: stable
    file: node-plugin.gitlab-ci.yml